DROP SCHEMA PADROES_PROJETOS;
CREATE SCHEMA PADROES_PROJETOS;

USE PADROES_PROJETOS;

DROP USER 'USER'@'LOCALHOST';
CREATE USER 'USER'@'LOCALHOST' IDENTIFIED BY 'PASS123';

GRANT SELECT, INSERT, DELETE, UPDATE ON PADROES_PROJETOS.* TO USER@'LOCALHOST';

CREATE TABLE USU_USUARIO(
    USU_ID BIGINT UNSIGNED AUTO_INCREMENT,
    USU_NOME_USUARIO VARCHAR(50) NOT NULL,
    USU_SENHA VARCHAR(50) NOT NULL,
    USU_NOME_EXIBICAO VARCHAR(64),

    CONSTRAINT UK_USU_NOME_USUARIO UNIQUE (USU_NOME_USUARIO),
    CONSTRAINT PK_USU_ID PRIMARY KEY (USU_ID)
);